include:
  - board: corneish_zen_v2_left
  - board: corneish_zen_v2_right
  - board: cornish_zen_v2_left
    shield: setting_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
  - board: cornish_zen_v2_right
    shield: setting_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
