include:
  - board: corneish_zen_v2_left
    shield: cornish_zen_v2_left
    snippet: studio-rpc-usb-uart
  - board: corneish_zen_v2_right
  - board: corneish_zen_v2_left
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
  - board: corneish_zen_v2_right
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
